<a href="https://colab.research.google.com/github/SwarupD21/Machine-Learning-Basics/blob/main/Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.random.randint(8,size=(2,3))
b=np.random.randint(8,size=(2,3))

In [ ]:
print(a)

[[5 0 3]
 [5 4 3]]


In [ ]:
a.shape

(2, 3)

In [ ]:
print(b)

[[3 5 6]
 [6 1 1]]


In [ ]:
b.shape

(2, 3)

**Addition of Matrix**

In [ ]:
summ=np.add(a,b)
print(summ)

[[ 8  5  9]
 [11  5  4]]


**Subtraction of Matrix**

In [ ]:
sub=np.subtract(a,b)

In [ ]:
print(sub)

[[ 2 -5 -3]
 [-1  3  2]]


**Matrix Multiplication**

In [ ]:
scalar_mul=np.multiply(5,a)
print(scalar_mul)

[[25  0 15]
 [25 20 15]]


In [ ]:
mul=np.multiply(a,b)
print(mul)

[[15  0 18]
 [30  4  3]]
