<a href="https://colab.research.google.com/github/SwarupD21/Machine-Learning-Basics/blob/main/Working_with_Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Creating a matrix using Numpy**

In [ ]:
matrix_1= np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [ ]:
matrix_1.shape

(2, 2)

In [ ]:
matrix2=np.array([[5,6,9],[1,2,4],[3,7,8]])
print(matrix2)

[[5 6 9]
 [1 2 4]
 [3 7 8]]


In [ ]:
matrix2.shape

(3, 3)

**Matrices with Random Values**

In [ ]:
mat3=np.random.rand(3,3)

In [ ]:
print(mat3)

[[0.75348583 0.19713079 0.60975499]
 [0.78819754 0.06708877 0.18008033]
 [0.26604481 0.64854584 0.27453619]]


**matrix with random integers**

In [ ]:
mat4=np.random.randint(100,size=(3,3))
print(mat4)

[[56 30 19]
 [89 99 96]
 [ 9 99 85]]


**1's Matrix**

In [ ]:
mat5=np.ones((2,3),dtype=int)
print(mat5)

[[1 1 1]
 [1 1 1]]


**Null Matrix**

In [ ]:
mat6=np.zeros((4,5),dtype=int)

In [ ]:
print(mat6)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


**Identity Matrix**

In [ ]:
mat7=np.eye(4,5,dtype=int)
print(mat7)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


**Transpose Matrix**

In [ ]:
mat8=np.random.randint(100,size=(4,5))
print(mat8)
transofmat8=np.transpose(mat8)

[[64 70 92 26 56]
 [54 74 27 40 14]
 [38 93 38 34 52]
 [80 16 22 46  0]]


In [ ]:
print(transofmat8)

[[64 54 38 80]
 [70 74 93 16]
 [92 27 38 22]
 [26 40 34 46]
 [56 14 52  0]]
